package com.example.ui.theme

import android.app.WallpaperManager
import android.content.Context
import android.graphics.Bitmap
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.LinearGradient
import android.graphics.Paint
import android.graphics.Shader
import androidx.compose.ui.graphics.Brush

data class ThemePreset(
    val id: String,
    val name: String,
    val description: String,
    val gradientStart: String,
    val gradientEnd: String,
    val textColor: String,
    val accentColor: String,
    val widgetBgColor: String,
    val widgetOpacity: Float,
    val defaultText: String,
    val styleType: String = "digital",
    val category: String = "AMOLED",
    val price: String = "Free",
    val originalPrice: String? = null,
    val isAnimated: Boolean = false,
    val rating: Float = 4.8f,
    val author: String = "Prism Design Studio",
    val downloads: String = "150K+"
) {
    fun getBrush(): Brush {
        return Brush.verticalGradient(
            listOf(
                androidx.compose.ui.graphics.Color(Color.parseColor(gradientStart)),
                androidx.compose.ui.graphics.Color(Color.parseColor(gradientEnd))
            )
        )
    }
}

object ThemePresets {
    val list = listOf(
        ThemePreset(
            id = "cosmic_dark",
            name = "Cosmic Slate",
            description = "Premium minimalist dark theme featuring deep space blues, celestial orbital paths, and glowing cyan neon highlights.",
            gradientStart = "#0B0C15",
            gradientEnd = "#1B1D30",
            textColor = "#FFFFFF",
            accentColor = "#00E5FF",
            widgetBgColor = "#121325",
            widgetOpacity = 0.85f,
            defaultText = "Design is intelligence made visible.",
            styleType = "digital",
            category = "AMOLED",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Galaxy Premium Team",
            downloads = "2.4M+"
        ),
        ThemePreset(
            id = "neon_cyberpunk",
            name = "Retro Cyberpunk",
            description = "High-fidelity retro-futuristic dark theme, inspired by vaporwave neon, deep magenta glows, and synthwave sunset tones.",
            gradientStart = "#06070C",
            gradientEnd = "#160C1B",
            textColor = "#FFFFFF",
            accentColor = "#FE2C55",
            widgetBgColor = "#0A050F",
            widgetOpacity = 0.75f,
            defaultText = "The future belongs to those who create it.",
            styleType = "analog",
            category = "Gaming",
            price = "Free",
            isAnimated = true,
            rating = 4.8f,
            author = "Synthetix Arts",
            downloads = "890K+"
        ),
        ThemePreset(
            id = "pastel_calm",
            name = "Aesthetic Pastel",
            description = "Cozy day-mode pastel vibes pairing soft lavender, warm frosted peach gradients, and clean minimalist styling.",
            gradientStart = "#FFF3EB",
            gradientEnd = "#F2EDFF",
            textColor = "#3C2F2F",
            accentColor = "#FF8E7A",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.70f,
            defaultText = "Pause, breathe, and enjoy the moment.",
            styleType = "calendar",
            category = "Minimal",
            price = "Free",
            rating = 4.6f,
            author = "Lofi Vibes Co",
            downloads = "350K+"
        ),
        ThemePreset(
            id = "forest_organic",
            name = "Sage Forest Wood",
            description = "Earthy biophilic sage green theme for nature lovers, bringing soothing forest elements and organic minimalism home.",
            gradientStart = "#1B241E",
            gradientEnd = "#2D3A30",
            textColor = "#EAF0EA",
            accentColor = "#A2B798",
            widgetBgColor = "#1D2821",
            widgetOpacity = 0.80f,
            defaultText = "Nature does not hurry, yet everything is accomplished.",
            styleType = "quote",
            category = "Nature",
            price = "Free",
            rating = 4.7f,
            author = "Gaia Elements",
            downloads = "120K+"
        ),
        ThemePreset(
            id = "sunset_warmth",
            name = "Sunset Vintage",
            description = "Nostalgic 70s-style vinyl layout consisting of deep crimson melting into vibrant golden-amber sunset glows.",
            gradientStart = "#180003",
            gradientEnd = "#4E1500",
            textColor = "#FFE6D5",
            accentColor = "#FFB300",
            widgetBgColor = "#2A0402",
            widgetOpacity = 0.85f,
            defaultText = "Every sunset brings the promise of a new dawn.",
            styleType = "digital",
            category = "Nature",
            price = "Free",
            rating = 4.9f,
            author = "Retro Wave Lab",
            downloads = "410K+"
        ),
        ThemePreset(
            id = "zen_sakura",
            name = "Zen Sakura Anime",
            description = "Handcrafted anime-style canvas detailing neon cherry blossoms falling gently against beautiful dark purple sky backdrops.",
            gradientStart = "#0B0516",
            gradientEnd = "#2D0A35",
            textColor = "#FFF0FA",
            accentColor = "#FF66B2",
            widgetBgColor = "#1E0422",
            widgetOpacity = 0.80f,
            defaultText = "The beauty of tomorrow shines within you.",
            styleType = "digital",
            category = "Anime",
            price = "Free",
            rating = 4.9f,
            isAnimated = false,
            author = "Vibrant Otaku Themes",
            downloads = "95K+"
        ),
        ThemePreset(
            id = "hypercar_gt",
            name = "Carbon Hypercar GT",
            description = "Extreme high-intensity automotive theme. Woven carbon fibers styled with electric yellow dynamic instruments.",
            gradientStart = "#0A0A0E",
            gradientEnd = "#1E1E28",
            textColor = "#FFFFFF",
            accentColor = "#FFD700",
            widgetBgColor = "#121217",
            widgetOpacity = 0.85f,
            defaultText = "Speed is a state of mind.",
            styleType = "analog",
            category = "Cars",
            price = "Free",
            rating = 5.0f,
            isAnimated = true,
            author = "Octane Studio",
            downloads = "550K+"
        ),
        ThemePreset(
            id = "shiva_eternal",
            name = "Shiva Cosmic Devotion",
            description = "A magnificent holy theme featuring divine golden space contours, celestial trident symbols, and deep cosmic meditative blue shades.",
            gradientStart = "#030A1C",
            gradientEnd = "#1A253E",
            textColor = "#F5F8FF",
            accentColor = "#FFA726",
            widgetBgColor = "#0A1124",
            widgetOpacity = 0.80f,
            defaultText = "Infinite consciousness resides within.",
            styleType = "quote",
            category = "God",
            price = "Free",
            rating = 5.0f,
            isAnimated = true,
            author = "Devotional Artworks",
            downloads = "1.2M+"
        ),
        ThemePreset(
            id = "nebula_forge",
            name = "Nebula Forge",
            description = "Interstellar sci-fi command center utilizing dark purple cosmic portals and glowing pink system indicators.",
            gradientStart = "#0D0C15",
            gradientEnd = "#25123E",
            textColor = "#FFFFFF",
            accentColor = "#F06292",
            widgetBgColor = "#130F25",
            widgetOpacity = 0.90f,
            defaultText = "Explore the boundless sky.",
            styleType = "digital",
            category = "Anime",
            price = "Free",
            rating = 4.7f,
            author = "Starlight Arts",
            downloads = "65K+"
        ),
        ThemePreset(
            id = "aura_quartz",
            name = "Aura Neon Quartz",
            description = "Brilliant holographic patterns with interactive cyan-purple glows on a pitch black AMOLED background.",
            gradientStart = "#000000",
            gradientEnd = "#120B1C",
            textColor = "#E1D5EC",
            accentColor = "#B388FF",
            widgetBgColor = "#0C0512",
            widgetOpacity = 0.75f,
            defaultText = "Live in the vibrant aura.",
            styleType = "digital",
            category = "AMOLED",
            price = "Free",
            rating = 4.8f,
            author = "OneUI Lab Team",
            downloads = "3.1M+"
        ),
        ThemePreset(
            id = "lavender_dream",
            name = "Lavender Dream",
            description = "Vaporous lavender day-mode gradient containing deep orchid flourishes and high-end modern layout details.",
            gradientStart = "#E8DBFC",
            gradientEnd = "#F8EBFD",
            textColor = "#4A1A6C",
            accentColor = "#9C27B0",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.82f,
            defaultText = "Live simple, dream big.",
            styleType = "calendar",
            category = "Pastel",
            price = "Free",
            rating = 4.8f,
            author = "Iris Lab Co",
            downloads = "240K+"
        ),
        ThemePreset(
            id = "solar_flare",
            name = "Solar Flare",
            description = "Intense deep-space magnetic solar currents bleeding neon amber and rich burnt sienna into complete darkness.",
            gradientStart = "#100400",
            gradientEnd = "#300D00",
            textColor = "#FFF0EA",
            accentColor = "#FF6D00",
            widgetBgColor = "#1D0700",
            widgetOpacity = 0.88f,
            defaultText = "Let your light shine.",
            styleType = "digital",
            category = "Space",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Galaxy Premium Team",
            downloads = "950K+"
        ),
        ThemePreset(
            id = "midnight_abyss",
            name = "Midnight Abyss",
            description = "Authentic full-pitch pitch-black AMOLED base styled with glowing fluorescent electric cyan cyber channels.",
            gradientStart = "#000000",
            gradientEnd = "#0A0B10",
            textColor = "#E1E2E5",
            accentColor = "#00E5FF",
            widgetBgColor = "#050608",
            widgetOpacity = 0.90f,
            defaultText = "Into the silent deep.",
            styleType = "digital",
            category = "AMOLED",
            price = "Free",
            rating = 5.0f,
            author = "OneUI Lab Team",
            downloads = "4.2M+"
        ),
        ThemePreset(
            id = "emerald_aurora",
            name = "Emerald Aurora",
            description = "Soothing dynamic Northern Lights curtain shifting deep pine-green and bright radioactive neon-emerald glows.",
            gradientStart = "#020E08",
            gradientEnd = "#072414",
            textColor = "#E8F5E9",
            accentColor = "#00E676",
            widgetBgColor = "#03170C",
            widgetOpacity = 0.85f,
            defaultText = "Dance with the northern lights.",
            styleType = "digital",
            category = "Nature",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Gaia Elements",
            downloads = "620K+"
        ),
        ThemePreset(
            id = "peach_sunset",
            name = "Peach Sunset",
            description = "Warm day-mode glowing peach and rich cream gradient, perfect for a modern minimalist aesthetic.",
            gradientStart = "#FFF3EE",
            gradientEnd = "#FFE5DC",
            textColor = "#5D4037",
            accentColor = "#FF7043",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.75f,
            defaultText = "Soft skies and warm vibes.",
            styleType = "calendar",
            category = "Minimal",
            price = "Free",
            rating = 4.7f,
            author = "Lofi Vibes Co",
            downloads = "150K+"
        ),
        ThemePreset(
            id = "glacier_chill",
            name = "Glacier Ice",
            description = "Serene frosted deep-sea antarctic ice sheet melting into gorgeous dark cerulean blue shades.",
            gradientStart = "#08131A",
            gradientEnd = "#162B38",
            textColor = "#E1F5FE",
            accentColor = "#29B6F6",
            widgetBgColor = "#0C1D26",
            widgetOpacity = 0.80f,
            defaultText = "As serene as frozen glaciers.",
            styleType = "quote",
            category = "Nature",
            price = "Free",
            rating = 4.8f,
            author = "Gaia Elements",
            downloads = "310K+"
        ),
        ThemePreset(
            id = "krishna_flute",
            name = "Krishna Devotion",
            description = "Elegant saffron-yellow and deep cosmic indigo gradient featuring gorgeous peacock contours and flute motifs.",
            gradientStart = "#050014",
            gradientEnd = "#15022D",
            textColor = "#FFFDE7",
            accentColor = "#FBC02D",
            widgetBgColor = "#0A001B",
            widgetOpacity = 0.85f,
            defaultText = "Peace in divine music.",
            styleType = "quote",
            category = "God",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Devotional Artworks",
            downloads = "1.8M+"
        ),
        ThemePreset(
            id = "tokyo_neon",
            name = "Tokyo Lights",
            description = "Highly futuristic nightlife aesthetic, blending neon magenta, Tokyo purple, and deep asphalt silhouettes.",
            gradientStart = "#060111",
            gradientEnd = "#1B022B",
            textColor = "#FFF1FD",
            accentColor = "#E040FB",
            widgetBgColor = "#10021D",
            widgetOpacity = 0.78f,
            defaultText = "Sleepless nights in neon city.",
            styleType = "digital",
            category = "Gaming",
            price = "Free",
            isAnimated = true,
            rating = 4.8f,
            author = "Synthetix Arts",
            downloads = "670K+"
        ),
        ThemePreset(
            id = "desert_dusk",
            name = "Desert Dusk",
            description = "Rustic ochre and desert sunset bronze tones, bringing natural warm sands to your screen.",
            gradientStart = "#1F0C05",
            gradientEnd = "#3E1A0C",
            textColor = "#FFECB3",
            accentColor = "#FFA726",
            widgetBgColor = "#2A1108",
            widgetOpacity = 0.83f,
            defaultText = "Winds of change blow soft.",
            styleType = "digital",
            category = "Nature",
            price = "Free",
            rating = 4.6f,
            author = "Prism Design Studio",
            downloads = "180K+"
        ),
        ThemePreset(
            id = "cyber_armor",
            name = "Cyber Shard",
            description = "Hi-tech military tactical armor pattern styled with high-voltage neon blue crystal guidelines.",
            gradientStart = "#0B0F19",
            gradientEnd = "#1A233A",
            textColor = "#ECEFF1",
            accentColor = "#00B0FF",
            widgetBgColor = "#0F1626",
            widgetOpacity = 0.85f,
            defaultText = "Upgrade your defense matrix.",
            styleType = "analog",
            category = "Gaming",
            price = "Free",
            rating = 4.7f,
            author = "Synthetix Arts",
            downloads = "410K+"
        ),
        ThemePreset(
            id = "sakura_spring",
            name = "Sakura Blossom",
            description = "Gentle pink cherry blossoms against a beautiful dark violet spring twilight canvas.",
            gradientStart = "#1A0A12",
            gradientEnd = "#3A1B29",
            textColor = "#FCE4EC",
            accentColor = "#F50057",
            widgetBgColor = "#260F1A",
            widgetOpacity = 0.80f,
            defaultText = "Spring is a state of mind.",
            styleType = "digital",
            category = "Anime",
            price = "Free",
            rating = 4.9f,
            author = "Vibrant Otaku Themes",
            downloads = "220K+"
        ),
        ThemePreset(
            id = "deep_oceanic",
            name = "Deep Ocean Escape",
            description = "Into the aquatic abyss. Beautiful shades of royal teal and pure sapphire blue.",
            gradientStart = "#010A14",
            gradientEnd = "#071A2E",
            textColor = "#E0F2F1",
            accentColor = "#00BFA5",
            widgetBgColor = "#031020",
            widgetOpacity = 0.85f,
            defaultText = "Dive deep into calm.",
            styleType = "quote",
            category = "Nature",
            price = "Free",
            rating = 4.8f,
            author = "Gaia Elements",
            downloads = "430K+"
        ),
        ThemePreset(
            id = "ganesha_wisdom",
            name = "Ganesha Blessings",
            description = "A sacred and auspicious theme, filled with golden orange fire rings and deep sandalwood backdrops.",
            gradientStart = "#210705",
            gradientEnd = "#48150D",
            textColor = "#FFFDE7",
            accentColor = "#FF9100",
            widgetBgColor = "#2D0A08",
            widgetOpacity = 0.88f,
            defaultText = "Remove all obstacles.",
            styleType = "quote",
            category = "God",
            price = "Free",
            rating = 4.9f,
            author = "Devotional Artworks",
            downloads = "1.5M+"
        ),
        ThemePreset(
            id = "golden_elegance",
            name = "Golden Luxury",
            description = "High-end bespoke luxury theme, painting real gold-leaf accents on high-contrast matte obsidian slate.",
            gradientStart = "#13110E",
            gradientEnd = "#2A261F",
            textColor = "#FFF8E1",
            accentColor = "#D4AF37",
            widgetBgColor = "#1D1915",
            widgetOpacity = 0.90f,
            defaultText = "Simplicity is the ultimate sophistication.",
            styleType = "analog",
            category = "Minimal",
            price = "Free",
            rating = 4.9f,
            author = "Prism Design Studio",
            downloads = "1.1M+"
        ),
        ThemePreset(
            id = "rose_quartz",
            name = "Rose Quartz",
            description = "Soft glowing pink day-mode crystal theme, celebrating calm floral gradients and elegant elements.",
            gradientStart = "#FFF5F8",
            gradientEnd = "#FFE5EE",
            textColor = "#4E3440",
            accentColor = "#EC407A",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.70f,
            defaultText = "Gentle loving energy.",
            styleType = "calendar",
            category = "Pastel",
            price = "Free",
            rating = 4.7f,
            author = "Iris Lab Co",
            downloads = "190K+"
        ),
        ThemePreset(
            id = "velocity_racing",
            name = "Velocity Track",
            description = "Intense motorsport elements. Dynamic carbon fibers accented with sharp high-contrast redlines.",
            gradientStart = "#0B0C0E",
            gradientEnd = "#1A1D24",
            textColor = "#FFFFFF",
            accentColor = "#D50000",
            widgetBgColor = "#111317",
            widgetOpacity = 0.85f,
            defaultText = "Drive at the speed of thought.",
            styleType = "analog",
            category = "Cars",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Octane Studio",
            downloads = "480K+"
        ),
        ThemePreset(
            id = "bubblegum_pop",
            name = "Bubblegum Pop",
            description = "Lively retro 80s arcade vibe, blending sweet pink bubblegum with intense electric orange accents.",
            gradientStart = "#14001F",
            gradientEnd = "#300244",
            textColor = "#FFE3FC",
            accentColor = "#FF3D00",
            widgetBgColor = "#1A0029",
            widgetOpacity = 0.80f,
            defaultText = "Fun, vibrant, energetic vibe.",
            styleType = "calendar",
            category = "Neon",
            price = "Free",
            rating = 4.7f,
            author = "Synthetix Arts",
            downloads = "320K+"
        ),
        ThemePreset(
            id = "matcha_green",
            name = "Matcha Tea",
            description = "Quiet afternoon Matcha. Soothing milky green base for high concentration and visual relief.",
            gradientStart = "#FAF9F5",
            gradientEnd = "#EAEADF",
            textColor = "#2F3E32",
            accentColor = "#4CAF50",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.75f,
            defaultText = "Calm your senses daily.",
            styleType = "calendar",
            category = "Minimal",
            price = "Free",
            rating = 4.8f,
            author = "Lofi Vibes Co",
            downloads = "460K+"
        ),
        ThemePreset(
            id = "electric_storm",
            name = "Thunder Strike",
            description = "Spectacular dark sky illuminated by dynamic electric cyan static lightning strikes.",
            gradientStart = "#020712",
            gradientEnd = "#0C1F3D",
            textColor = "#E0F7FA",
            accentColor = "#1DE9B6",
            widgetBgColor = "#051125",
            widgetOpacity = 0.84f,
            defaultText = "Ride the electric storm.",
            styleType = "digital",
            category = "Space",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Galaxy Premium Team",
            downloads = "780K+"
        ),
        ThemePreset(
            id = "crimson_fury",
            name = "Crimson Vanguard",
            description = "Bespoke gaming battle layout featuring carbon blood gradients and high-end metallic highlights.",
            gradientStart = "#140103",
            gradientEnd = "#320409",
            textColor = "#FFEBEE",
            accentColor = "#FF1744",
            widgetBgColor = "#1C0205",
            widgetOpacity = 0.88f,
            defaultText = "Unfold ultimate power.",
            styleType = "analog",
            category = "Gaming",
            price = "Free",
            rating = 4.8f,
            author = "Synthetix Arts",
            downloads = "590K+"
        ),
        ThemePreset(
            id = "jesus_divine",
            name = "Divine Mercy",
            description = "A peaceful holy theme presenting warm rays of spiritual hope on deep sapphire-cloud backdrops.",
            gradientStart = "#0A141C",
            gradientEnd = "#1A3246",
            textColor = "#ECEFF1",
            accentColor = "#4FC3F7",
            widgetBgColor = "#0F202D",
            widgetOpacity = 0.85f,
            defaultText = "Grace and hope eternal.",
            styleType = "quote",
            category = "God",
            price = "Free",
            rating = 4.9f,
            author = "Devotional Artworks",
            downloads = "980K+"
        ),
        ThemePreset(
            id = "autumn_leaf",
            name = "Autumn Leaf",
            description = "Rich copper, warm cinnamon, and deep amber trees shedding beautiful dynamic leaves.",
            gradientStart = "#260F03",
            gradientEnd = "#4E2108",
            textColor = "#FFE0B2",
            accentColor = "#FF6D00",
            widgetBgColor = "#331505",
            widgetOpacity = 0.80f,
            defaultText = "A beautiful ending in amber.",
            styleType = "quote",
            category = "Nature",
            price = "Free",
            rating = 4.7f,
            author = "Gaia Elements",
            downloads = "210K+"
        ),
        ThemePreset(
            id = "vintage_polar",
            name = "Polar Snow",
            description = "Ultra minimalist frosted daylight theme. Perfect high contrast for bright daylight screens.",
            gradientStart = "#F2F4F7",
            gradientEnd = "#DDE2E8",
            textColor = "#263238",
            accentColor = "#37474F",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.80f,
            defaultText = "Crisp, clean, minimalist focus.",
            styleType = "digital",
            category = "Minimal",
            price = "Free",
            rating = 4.7f,
            author = "Prism Design Studio",
            downloads = "340K+"
        ),
        ThemePreset(
            id = "drift_spec",
            name = "Drift Horizon",
            description = "Sleek automotive design displaying asphalt road textures and cyan drift tire marks.",
            gradientStart = "#08080C",
            gradientEnd = "#151520",
            textColor = "#ECEFF1",
            accentColor = "#00E5FF",
            widgetBgColor = "#0D0D14",
            widgetOpacity = 0.85f,
            defaultText = "Slide through the corners.",
            styleType = "analog",
            category = "Cars",
            price = "Free",
            rating = 4.8f,
            author = "Octane Studio",
            downloads = "360K+"
        ),
        ThemePreset(
            id = "mint_breeze",
            name = "Mint Breeze",
            description = "Slightly sweet teal and fresh mint leaf day-mode gradient, creating peace and visual safety.",
            gradientStart = "#F1FAF6",
            gradientEnd = "#D9EDE5",
            textColor = "#1E3D30",
            accentColor = "#00C853",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.75f,
            defaultText = "Refreshing and rejuvenating.",
            styleType = "calendar",
            category = "Pastel",
            price = "Free",
            rating = 4.8f,
            author = "Lofi Vibes Co",
            downloads = "270K+"
        ),
        ThemePreset(
            id = "indigo_nebula",
            name = "Indigo Nebula",
            description = "Beautiful indigo stellar gas clouds drifting silently across infinite starfields.",
            gradientStart = "#050014",
            gradientEnd = "#170233",
            textColor = "#ECE5FF",
            accentColor = "#D500F9",
            widgetBgColor = "#0B0024",
            widgetOpacity = 0.88f,
            defaultText = "Lost in cosmic thoughts.",
            styleType = "digital",
            category = "Space",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Galaxy Premium Team",
            downloads = "810K+"
        ),
        ThemePreset(
            id = "royal_purple",
            name = "Velvet Crown",
            description = "Premium velvet violet tones melting into deep black AMOLED backgrounds, fit for royalty.",
            gradientStart = "#000000",
            gradientEnd = "#14011E",
            textColor = "#F3E5F5",
            accentColor = "#AA00FF",
            widgetBgColor = "#08000C",
            widgetOpacity = 0.90f,
            defaultText = "Sovereign design patterns.",
            styleType = "digital",
            category = "AMOLED",
            price = "Free",
            rating = 4.9f,
            author = "OneUI Lab Team",
            downloads = "1.2M+"
        ),
        ThemePreset(
            id = "golden_temple",
            name = "Amritsar Glow",
            description = "Mystical golden sun reflecting off high temple waters under deep starry night skies.",
            gradientStart = "#170C01",
            gradientEnd = "#331D03",
            textColor = "#FFFDF0",
            accentColor = "#FFD700",
            widgetBgColor = "#221202",
            widgetOpacity = 0.87f,
            defaultText = "Divine peace in golden reflection.",
            styleType = "quote",
            category = "God",
            price = "Free",
            rating = 4.9f,
            author = "Devotional Artworks",
            downloads = "640K+"
        ),
        ThemePreset(
            id = "cyberpunk_grid",
            name = "Cyber Grid",
            description = "A synthetic cyber grid mapping custom vertical matrix codes and retro fluorescent cyan lines.",
            gradientStart = "#030207",
            gradientEnd = "#0E0820",
            textColor = "#F1E5FF",
            accentColor = "#00E5FF",
            widgetBgColor = "#080414",
            widgetOpacity = 0.80f,
            defaultText = "Grid of electric neon dreams.",
            styleType = "digital",
            category = "Neon",
            price = "Free",
            isAnimated = true,
            rating = 4.8f,
            author = "Synthetix Arts",
            downloads = "890K+"
        ),
        ThemePreset(
            id = "panda_mono",
            name = "Panda Contrast",
            description = "Extreme high-contrast monochrome design, pairing absolute white blocks with pitch-black screens.",
            gradientStart = "#050505",
            gradientEnd = "#181818",
            textColor = "#FFFFFF",
            accentColor = "#FFFFFF",
            widgetBgColor = "#0A0A0A",
            widgetOpacity = 0.93f,
            defaultText = "Contrast is the essence of clarity.",
            styleType = "digital",
            category = "Minimal",
            price = "Free",
            rating = 4.7f,
            author = "Prism Design Studio",
            downloads = "550K+"
        ),
        ThemePreset(
            id = "synthwave_sunset",
            name = "Synthwave Sunset",
            description = "Dynamic synth sunset grid, projecting warm reddish pink flares onto cosmic star skies.",
            gradientStart = "#05020D",
            gradientEnd = "#1D092E",
            textColor = "#FFF0FA",
            accentColor = "#FE2C55",
            widgetBgColor = "#110420",
            widgetOpacity = 0.82f,
            defaultText = "Drive into the endless sunset.",
            styleType = "digital",
            category = "Gaming",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Synthetix Arts",
            downloads = "1.1M+"
        ),
        ThemePreset(
            id = "forest_fog",
            name = "Misty Woodlands",
            description = "Serene biophilic layout pairing rich pine green with misty silver wood backdrops.",
            gradientStart = "#0F1512",
            gradientEnd = "#202E27",
            textColor = "#E0EBE2",
            accentColor = "#81C784",
            widgetBgColor = "#151F1B",
            widgetOpacity = 0.80f,
            defaultText = "Peace found under canopy trees.",
            styleType = "quote",
            category = "Nature",
            price = "Free",
            rating = 4.7f,
            author = "Gaia Elements",
            downloads = "280K+"
        ),
        ThemePreset(
            id = "neon_pulse",
            name = "Electric Cyan",
            description = "Rhythmic high-fidelity soundwave traces in bright cyan floating over AMOLED black space.",
            gradientStart = "#00050D",
            gradientEnd = "#00122B",
            textColor = "#E0F7FA",
            accentColor = "#00E5FF",
            widgetBgColor = "#000B1B",
            widgetOpacity = 0.83f,
            defaultText = "Pulse to a digital beat.",
            styleType = "digital",
            category = "Neon",
            price = "Free",
            rating = 4.8f,
            author = "OneUI Lab Team",
            downloads = "410K+"
        ),
        ThemePreset(
            id = "celestial_comet",
            name = "Halley Comet",
            description = "A magnificent stardust trail detailing beautiful cyber spheres floating over velvet sky coordinates.",
            gradientStart = "#010512",
            gradientEnd = "#071333",
            textColor = "#E1F5FE",
            accentColor = "#80DEEA",
            widgetBgColor = "#030C25",
            widgetOpacity = 0.85f,
            defaultText = "Once in a lifetime view.",
            styleType = "digital",
            category = "Space",
            price = "Free",
            rating = 4.7f,
            author = "Galaxy Premium Team",
            downloads = "230K+"
        ),
        ThemePreset(
            id = "sakura_petals",
            name = "Blossom Petals",
            description = "Extremely soft, high-contrast day-mode pastel cherry blossom petals drifting slowly.",
            gradientStart = "#FFF8FA",
            gradientEnd = "#FFE5EC",
            textColor = "#5C3E48",
            accentColor = "#F06292",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.72f,
            defaultText = "Dainty petals drifting slow.",
            styleType = "calendar",
            category = "Minimal",
            price = "Free",
            rating = 4.8f,
            author = "Lofi Vibes Co",
            downloads = "190K+"
        ),
        ThemePreset(
            id = "carbon_redline",
            name = "Carbon Redline",
            description = "High-pressure carbon fibers styled with extreme bright red dashboard indicators.",
            gradientStart = "#0C0606",
            gradientEnd = "#200E0E",
            textColor = "#FFF1F1",
            accentColor = "#FF3D00",
            widgetBgColor = "#130A0A",
            widgetOpacity = 0.85f,
            defaultText = "Push your boundaries to edge.",
            styleType = "analog",
            category = "Cars",
            price = "Free",
            rating = 4.9f,
            author = "Octane Studio",
            downloads = "470K+"
        ),
        ThemePreset(
            id = "mystic_lotus",
            name = "Cosmic Lotus",
            description = "Magical meditative lotus blooming inside glowing ultraviolet celestial backdrops.",
            gradientStart = "#0E0417",
            gradientEnd = "#230A38",
            textColor = "#F3E5F5",
            accentColor = "#BA68C8",
            widgetBgColor = "#160A24",
            widgetOpacity = 0.82f,
            defaultText = "Pure thoughts rise from deep mud.",
            styleType = "quote",
            category = "God",
            price = "Free",
            rating = 4.8f,
            author = "Devotional Artworks",
            downloads = "380K+"
        ),
        ThemePreset(
            id = "bubble_tea",
            name = "Boba Caramel",
            description = "Cozy and delicious caramel day-mode theme featuring sweet milk boba illustrations.",
            gradientStart = "#FEF6F0",
            gradientEnd = "#F2E2D5",
            textColor = "#5D4037",
            accentColor = "#B10DC9",
            widgetBgColor = "#FFFFFF",
            widgetOpacity = 0.75f,
            defaultText = "Warm caramel boba vibes.",
            styleType = "calendar",
            category = "Pastel",
            price = "Free",
            rating = 4.8f,
            author = "Lofi Vibes Co",
            downloads = "290K+"
        ),
        ThemePreset(
            id = "stealth_matte",
            name = "Stealth Shadow",
            description = "Professional ultra-dark completely matte theme utilizing subtle stone grey accent lines.",
            gradientStart = "#020202",
            gradientEnd = "#0E0E0E",
            textColor = "#B0BEC5",
            accentColor = "#90A4AE",
            widgetBgColor = "#070707",
            widgetOpacity = 0.95f,
            defaultText = "Silent and completely invisible.",
            styleType = "digital",
            category = "AMOLED",
            price = "Free",
            rating = 4.9f,
            author = "OneUI Lab Team",
            downloads = "1.4M+"
        ),
        ThemePreset(
            id = "neon_viper",
            name = "Neon Emerald",
            description = "Venomous toxic green outlines glowing brightly against infinite deep space black canvases.",
            gradientStart = "#010803",
            gradientEnd = "#061F0F",
            textColor = "#E8F5E9",
            accentColor = "#00E676",
            widgetBgColor = "#031208",
            widgetOpacity = 0.84f,
            defaultText = "Venomous glow in pitch darkness.",
            styleType = "digital",
            category = "Gaming",
            price = "Free",
            isAnimated = true,
            rating = 4.9f,
            author = "Synthetix Arts",
            downloads = "720K+"
        )
    )

    fun get(id: String): ThemePreset {
        return list.find { it.id == id } ?: list[0]
    }

    fun applySystemWallpaper(context: Context, themeId: String): Boolean {
        return try {
            val preset = get(themeId)
            val wallpaperManager = WallpaperManager.getInstance(context)
            
            val width = 1080
            val height = 1920
            val bitmap = Bitmap.createBitmap(width, height, Bitmap.Config.ARGB_8888)
            val canvas = Canvas(bitmap)
            
            // Draw gradient background
            val paint = Paint().apply {
                isAntiAlias = true
                val colorStart = Color.parseColor(preset.gradientStart)
                val colorEnd = Color.parseColor(preset.gradientEnd)
                shader = LinearGradient(0f, 0f, 0f, height.toFloat(), colorStart, colorEnd, Shader.TileMode.CLAMP)
            }
            canvas.drawRect(0f, 0f, width.toFloat(), height.toFloat(), paint)
            
            // Draw elegant glowing ambient orbital paths/circles matching accent color
            val accentColor = Color.parseColor(preset.accentColor)
            val ambientPaint = Paint().apply {
                isAntiAlias = true
                color = Color.argb(60, Color.red(accentColor), Color.green(accentColor), Color.blue(accentColor))
                style = Paint.Style.FILL
            }
            canvas.drawCircle(width * 0.15f, height * 0.85f, width * 0.45f, ambientPaint)
            
            val secondAmbientPaint = Paint().apply {
                isAntiAlias = true
                color = Color.argb(40, Color.red(accentColor), Color.green(accentColor), Color.blue(accentColor))
                style = Paint.Style.FILL
            }
            canvas.drawCircle(width * 0.85f, height * 0.15f, width * 0.35f, secondAmbientPaint)
            
            // Set wallpaper on BOTH home and lock screens to apply completely
            if (android.os.Build.VERSION.SDK_INT >= android.os.Build.VERSION_CODES.N) {
                wallpaperManager.setBitmap(bitmap, null, true, WallpaperManager.FLAG_SYSTEM or WallpaperManager.FLAG_LOCK)
            } else {
                wallpaperManager.setBitmap(bitmap)
            }
            true
        } catch (e: Throwable) {
            android.util.Log.e("ThemePresets", "Error setting dynamic system wallpaper", e)
            false
        }
    }
}
